### ISSUE TITLE
Try building with meson

### ISSUE THREAD

**Issue by ev-br** [ev-br/mc_lib#14]
cf https://github.com/scipy/scipy/issues/13615

**Comment by ev-br** [comment]
cf https://github.com/FRidh/mesonpep517examples

**Comment by ev-br** [comment]
- [ ] унести __check_rndm в тесты, скомп там; 
- [ ] test w/pytest
- [ ] add to CI (Linux first?) 
- [ ] pip install /pep517
- [ ] client code: build ising1D w/setup.py
- [ ] move ising1d to meson, too
- [ ] document the process

**Comment by noDGodyaev** [comment]
CI for meson build

- [x] run tests from another dir (does not work)
- [x] change /tests location (need move `/tests` two level upper `mc_lib/mc_lib`)
- [x]  use `pytests --pyargs` (**works fine**)

- [ ] rename mc_lib/mc_lib (**works fine**, locally pytest passes, github workflow failed ) _in progress_
- [ ] use meson without pep517

**Comment by noDGodyaev** [comment]
Checking MacOS dev tests, compile section:

 `C++11`:
https://github.com/noDGodyaev/mc_lib/runs/3105157098
There see something like:
```console
mc_lib/observable.cpp:1978:9: warning: use of the 'fallthrough' attribute is a C++17 extension [-Wc++17-extensions]
        CYTHON_FALLTHROUGH;
        ^
```

I am tried to use `C++17`, it worked but returned some warnings:
https://github.com/noDGodyaev/mc_lib/pull/3/checks?check_run_id=3117367045 

@ev-br. Will it be useful to change the language version?

**Comment by ev-br** [comment]
Warnings about `tp_print` seems to have always been there, https://github.com/ev-br/mc_lib/runs/3105067732#step:5:5386
so it's probably harmless. I'm a little uneasy on why it did work with setuptools but needs a bump with meson, but it probably is OK if keeping C++11 is difficult.

**Comment by noDGodyaev** [comment]
Some time later:
Steps to restore windows support in CI\local

- [ ] fix my local win environments
- [ ] make 'hello Cython' with meson, using conda and venv
- [ ] test 'hello Cython' with Github Actions

- [ ] build mc_lib locally
- [ ] test mc_lib with Github Actions

**Comment by noDGodyaev** [comment]
About `--cplus` cython flag in meson >= 0.59
Some useful links:
SCIPY:
https://github.com/rgommers/scipy/issues/25
https://github.com/rgommers/scipy/pull/23#issuecomment-868983390

MESON issues:
https://github.com/mesonbuild/meson/issues/9015
https://github.com/mesonbuild/meson/pull/9017

Solution, that will be done in a few days:
> use `override_options` https://mesonbuild.com/howtox.html#set-default-cc-language-version

Broken
```meson
py3.extension_module(
  'observable', _observable_cpp,
  include_directories: inc_np,
  dependencies : py3_dep,
  install: true,
  subdir: install_dir,
  cython_args: '--cplus'  #<- this arg does not pass into compilation
)
```

Solution `22.07.2021`
```meson
_observable_cpp = custom_target('observable_cpp',
  output : 'observable.cpp',
  input : 'observable.pyx',
  command : [cython, '--cplus', '-3', '--fast-fail', '@INPUT@', '-o', '@OUTPUT@']
)

py3.extension_module(
  'observable', _observable_cpp,
  include_directories: inc_np,
  dependencies : [py3_dep],
  install: true,
  subdir: install_dir
)
```

**Comment by ev-br** [comment]
(mostly) closed by gh-30 : meson build now works, there are several kinks which are better tracked separately. So closing this.
