### ISSUE TITLE
shell wrapper meson

### ISSUE THREAD

**Issue by noDGodyaev** [ev-br/mc_lib#40]
Do we actually need a shell script? 

before #29, it made sense. Playing with flags etc. Now it contains only 2 lines of build code and export PYTHONPATH.
Check https://github.com/noDGodyaev/mc_lib/pull/1 for details.

The main question: for what purposes this script will be used? 

1. For developers:  building package with one line - than the solution is done
2. For CI dev tests to make them cleaner. I checked this: 
export PYTHONPATH inside script doesn't affect on `run` cell. (some Github Actions magic)
So the solution: pytest cell can be moved into scripts.
3. If @ev-br  have any ideas, I can add them and check them.

That's my solution for now.
```shell
meson setup builddir --prefix=$PWD/installdir
meson install -C builddir
# Get python version for PYHTONPATH
ver=$(python -V 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1.\2/')
export PYTHONPATH=$PWD/installdir/lib/python$ver/site-packages/
pytest mc_lib -v --pyargs
```

**Comment by ev-br** [comment]
It's definitely the first one. No need to keep fighting the gh actions. Some sort of script is certainly useful, even if only a convenience record for on-and-off users.

**Comment by ev-br** [comment]
Having mulled it over a bit, I think we should now merge in your current version. Mostly for documentation for the library --- the main usage is downstream, so we'll iterate based on that.

**Comment by ev-br** [comment]
all done: gh-41 is merged, README is updated in https://github.com/ev-br/mc_lib/commit/6dfae32edbc04b1c039820e2af13d8e80130a918
